views:
  v1/nodes:
    sortColumn: AGE:asc
    columns:
      - AGE
      - ID:.spec.providerID
      - TYPE:.metadata.labels.node\.kubernetes\.io/instance-type
      - POOL:.metadata.labels.karpenter\.sh/nodepool
      - STATUS
      - TAINTS
  v1/pods:
    columns:
      - SHARD:.metadata.labels.materialize\.cloud/organization-name
      - CLUSTER:.metadata.annotations.cluster\.environmentd\.materialize\.cloud/cluster-name|R
